"""
Django settings for shoply project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from logging.handlers import RotatingFileHandler
import os

# Load the environment variables from .env file
load_dotenv()

# Access the environment variables using os.getenv()
KAGGLE_USERNAME = os.getenv('KAGGLE_USERNAME')
KAGGLE_KEY = os.getenv('KAGGLE_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6bi$%f8znbdv4xqc5^9a%+%u-pmt2k_jg8+*%_q_c%=yh)nh%w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # Temp variable!! Must be updated before deployment!!!


CSRF_TRUSTED_ORIGINS = ['https://8000-patrickaod-shoply-mzy1w1e8zbe.ws.codeinstitute-ide.net'] # Temp variable!! Must be updated before deployment!!!



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth', # required for 'allauth' functionality
    'allauth.account', # required for 'allauth' account management
    'allauth.socialaccount', # required for 'allauth' social media authentication

    # Allauth social media login Providers
    #'allauth.socialaccount.providers.facebook', # Facebook
    #'allauth.socialaccount.providers.google', # Google
    #'allauth.socialaccount.providers.twitter', # Twitter
    
    #Project Applications
    'shoply',
    'home',
    'products',
    'bag',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware", # Allauth account middleware
]

ROOT_URLCONF = 'shoply.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates', 'allauth'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # required by allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.contexts.categories_processor', # required by navbar category dropdown
                'bag.contexts.bag_contents', # required for global bag access
            ],
        },
    },
]

#Message Storing
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

AUTHENTICATION_BACKENDS = [
    
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
    
]

# Allauth regular account configuration 
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
TrueACCOUNT_USERNAME_MIN_LENGTH = 4
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

# Testing email back-end
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Web Server Gateway Interface
WSGI_APPLICATION = 'shoply.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Loggers Settings

# Define the logs directory relative to BASE_DIR
LOGGING_DIR = os.path.join(BASE_DIR, 'logs')

if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)  # Create logs directory if it doesn't exist

# Loggers Configuration
LOGGING = {
    'version': 1,  # Use version 1 for Django logging configuration
    'disable_existing_loggers': False,  # Keeps the default Django loggers enabled
    'formatters': {
        'verbose': {  # Defines a format for more detailed logging output
            'format': '[{asctime}] {levelname} {module}: {message}',
            'style': '{',  # Allows Python 3's `{}` string formatting
            'datefmt': '%d/%m/%Y %H:%M:%S',  # UK-readable format: DD/MM/YYYY HH:MM:SS
        },
        'simple': {  # Simpler format for quick debugging
            'format': '{levelname}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {  # Console handler to output logs to the terminal
            'level': 'DEBUG', # Capture all logs at set level and below
            'class': 'logging.StreamHandler',
            'formatter': 'simple',  # Uses the 'simple' formatter defined above
        },
        'file': {  # File handler to write logs to a file
            'level': 'WARNING',  # Capture all logs at set level and above
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),  # Specify log file location
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,  # Keep 5 old log files
            'formatter': 'verbose',  # Uses the 'verbose' formatter for detailed output
        },
    },
    'loggers': {
        '': {  # Root logger - captures all logs
            'handlers': ['console', 'file'],  # Logs to both console and file
            'level': 'INFO',  # Default log level
        },
        'django': {  # Logger specifically for Django logs
            'handlers': ['console', 'file'],
            'level': 'INFO',  
            'propagate': False,  # Prevents logs from propagating to the root logger
        },
        'django.request': {  # Logger specifically for HTTP request logs
            'handlers': ['file'],
            'level': 'ERROR',  # Log only errors related to requests
            'propagate': False,
        },
        'shoply': {  # Custom logger you can use in your applications
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Set lower for detailed logs when debugging
            'propagate': False,
        },
    },
}

# Delivery Variables

FREE_DELIVERY_THRESHOLD = 50
STANDARD_DELIVERY_PERCENTAGE = 10