# Generated by Django 5.1.2 on 2024-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('imgUrl', models.URLField()),
                ('productURL', models.URLField()),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isBestSeller', models.BooleanField(default=False)),
                ('boughtInLastMonth', models.BooleanField(default=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
    ]
